### PR TITLE
Cyrillic symbols support

### PR DESCRIPTION
**Pull request by bodryi**
Hello! I worked with your library and faced a problem with russian letters. You hardcoded `utf-8 encoding` and because of that if I write data, that I read from ADS will look like this:
without_cyrillic_param
I found out, that if I remove `utf-8 encoding` (node.js by default sets it to `null`) it will get cyrillic data correctly:
with_cyrillic_param
I added optional parameter `cyrillic` to `get` and `getSync` methods, so it won't brake previous code, that used this library. By default it is set to `false`. Also, my code is fully covered with tests.

Hope, you'll acccept my PR it will help more people use this library for making great apps.

### CODE REVIEW

**Comment by juncaixinchi** [comment]
Are you sure that the `utf-8 encoding` caused the problem ?  If set `null`,  the raw buffer is returned.

I can't repeat your problem, you may describe more details or show me your code.

In my test, russian letters is OK, you may try following code:

```js
// a.js
const fs =require('fs')
const ads = require('./index')

const path = './some.txt'
const stream = 'user.fs-ads.test'
const data = 'English 中文 Русский язык'

ads.setSync(path, stream, data)
console.log('data: ', data)
console.log('read: ', ads.getSync(path, stream))
```
script  in bash
```bash
cd fs-ads
touch some.txt
node a.js
notepad some.txt:user.fs-ads.test
```

my result:

fs-ads

**Comment by bodryi** [comment]
```
const fs = require('fs');
const ads = require('./index');

res = ads.getSync(targetFolder + filename, adsname);
fs.writeFile(targetFolder + filename.substring(0, filename.lastIndexOf('.exe')) + '.txt', res, (err) => {
   if (err) throw err;
   console.log('Data from ADS was succesfully saved to txt file!');
})
```
In my case, I have .exe file in `targetFolder` with `filename`. Someone wrote russian letters in ADS with `adsname`. I read it from here and worte down to new .txt file with the same name. You can see the result with `utf-8` and without it on screenshots above.

**Comment by juncaixinchi** [comment]
I guess that someone wrote the ADS in some encoding diff from `utf-8`. So It's a problem of encoding, not just unsupporting of cyrillic symbols.

if you could get the right data without the `utf-8` parameter, you can try to add a buffer transform before writing to the file, it should work as well.
```js
const res = Buffer.from(ads.getSync(targetFolder + filename, adsname));
// or
const res = Buffer.from(ads.getSync(targetFolder + filename, adsname), 'some encodeing');
```

**Comment by bodryi** [comment]
I changed 
```const res = ads.getSync(targetFolder + filename, adsname);```
to
```const res =  Buffer.from(readADSSync(targetFolder, filename));```
and it did't help. By default it is set to ```utf-8``` and I get the same ```???``` symbols. If I try to change encoding to any other, e.g. ```ascii``` I'll got this
currupted_file
but should see this
image

**Comment by juncaixinchi** [comment]
I have updated this repo https://github.com/juncaixinchi/fs-ads/commit/2d23a54a81b62aceead0d27e49da5245daa30125  . You can add an option to  specify the encoding. 

In your case, `{ encoding: null }` should work.

```
res = ads.getSync(targetFolder + filename, adsname, { encoding: null });
```

And thank you for your pull request. However, I think it's better to add an extra option which is more universal.

**Pull request closed without merging**
